import { NextRequest, NextResponse } from "next/server";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { uploadsRoot } from "@/lib/upload";

const CONTENT_TYPES: Record<string, string> = {
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  png: "image/png",
  webp: "image/webp",
};

// Uploaded photo filenames are always <uuid>.<ext>, generated by saveDoctorPhoto —
// reject anything else so a crafted path can't escape the uploads directory.
const SAFE_FILENAME = /^[a-f0-9-]+\.(jpg|jpeg|png|webp)$/i;

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ filename: string }> }
) {
  const { filename } = await params;
  if (!SAFE_FILENAME.test(filename)) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const ext = filename.split(".").pop()!.toLowerCase();
  try {
    const bytes = await readFile(join(uploadsRoot(), "doctors", filename));
    return new NextResponse(new Uint8Array(bytes), {
      headers: {
        "Content-Type": CONTENT_TYPES[ext],
        "Cache-Control": "public, max-age=31536000, immutable",
      },
    });
  } catch {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }
}
